site_name: hyperc

theme:
  name: material
  logo: assets/images/logo.jpg
  favicon: assets/images/logo.jpg
  palette:
    - scheme: slate
      primary: black
      accent: red

  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.instant
    - content.code.copy
    - search.highlight
    - search.suggest
    - search.highlight
    - search.suggest



pluginscustom_dir: 
  - search:
      lang: en
  - awesome-pages


extra_css:
  - assets/stylesheets/extra.css